/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminBooksRouteImport } from './routes/admin.books'
import { Route as AdminCirculationRouteImport } from './routes/admin.circulation'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as StudentCatalogRouteImport } from './routes/student.catalog'
import { Route as StudentHomeRouteImport } from './routes/student.home'
import { Route as StudentLibraryRouteImport } from './routes/student.library'
import { Route as StudentProfileRouteImport } from './routes/student.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/admin/books',
  path: '/admin/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCirculationRoute = AdminCirculationRouteImport.update({
  id: '/admin/circulation',
  path: '/admin/circulation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCatalogRoute = StudentCatalogRouteImport.update({
  id: '/student/catalog',
  path: '/student/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentHomeRoute = StudentHomeRouteImport.update({
  id: '/student/home',
  path: '/student/home',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLibraryRoute = StudentLibraryRouteImport.update({
  id: '/student/library',
  path: '/student/library',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/circulation': typeof AdminCirculationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/members': typeof AdminMembersRoute
  '/student/catalog': typeof StudentCatalogRoute
  '/student/home': typeof StudentHomeRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/profile': typeof StudentProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/circulation': typeof AdminCirculationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/members': typeof AdminMembersRoute
  '/student/catalog': typeof StudentCatalogRoute
  '/student/home': typeof StudentHomeRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/profile': typeof StudentProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/circulation': typeof AdminCirculationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/members': typeof AdminMembersRoute
  '/student/catalog': typeof StudentCatalogRoute
  '/student/home': typeof StudentHomeRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/profile': typeof StudentProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/books'
    | '/admin/circulation'
    | '/admin/dashboard'
    | '/admin/members'
    | '/student/catalog'
    | '/student/home'
    | '/student/library'
    | '/student/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/books'
    | '/admin/circulation'
    | '/admin/dashboard'
    | '/admin/members'
    | '/student/catalog'
    | '/student/home'
    | '/student/library'
    | '/student/profile'
  id:
    | '__root__'
    | '/'
    | '/admin/books'
    | '/admin/circulation'
    | '/admin/dashboard'
    | '/admin/members'
    | '/student/catalog'
    | '/student/home'
    | '/student/library'
    | '/student/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminBooksRoute: typeof AdminBooksRoute
  AdminCirculationRoute: typeof AdminCirculationRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMembersRoute: typeof AdminMembersRoute
  StudentCatalogRoute: typeof StudentCatalogRoute
  StudentHomeRoute: typeof StudentHomeRoute
  StudentLibraryRoute: typeof StudentLibraryRoute
  StudentProfileRoute: typeof StudentProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/admin/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/circulation': {
      id: '/admin/circulation'
      path: '/admin/circulation'
      fullPath: '/admin/circulation'
      preLoaderRoute: typeof AdminCirculationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/catalog': {
      id: '/student/catalog'
      path: '/student/catalog'
      fullPath: '/student/catalog'
      preLoaderRoute: typeof StudentCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/home': {
      id: '/student/home'
      path: '/student/home'
      fullPath: '/student/home'
      preLoaderRoute: typeof StudentHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/library': {
      id: '/student/library'
      path: '/student/library'
      fullPath: '/student/library'
      preLoaderRoute: typeof StudentLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminBooksRoute: AdminBooksRoute,
  AdminCirculationRoute: AdminCirculationRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMembersRoute: AdminMembersRoute,
  StudentCatalogRoute: StudentCatalogRoute,
  StudentHomeRoute: StudentHomeRoute,
  StudentLibraryRoute: StudentLibraryRoute,
  StudentProfileRoute: StudentProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
